"""Raiz do alvo, a pasta gerada (STATE_DIR), realpath, classificação e globs.

Regras (ARCHITECTURE.md §8):
- raiz = argumento explícito > $CLAUDE_PROJECT_DIR > cwd; NUNCA o diretório do script;
- todo path passa por realpath antes de ser classificado/escrito (anti-symlink);
- fixture/vendor/generated são ignorados por todo consumidor (mas listados no inventário);
- nomes reservados casam por PREFIXO de path, não por componente.
"""

import os
import re

from .errors import CsError

# Pasta gerada no alvo: FONTE ÚNICA do nome (o motor copiado ao alvo espelha em hcore.STATE_DIR).
STATE_DIR = ".swarm"
# Nome legado (até a iteração 8): só para detecção/migração (cs.py upgrade, rename-dir). Nunca escrito.
LEGACY_STATE_DIR = ".specialists"
SPECIALISTS_DIRNAME = STATE_DIR  # alias histórico (mesmo valor de STATE_DIR)

# Categorias de arquivo. IGNORED_CATEGORIES nunca entram em análise nem em território.
CAT_PRODUCT = "product"
CAT_FIXTURE = "fixture"
CAT_VENDOR = "vendor"
CAT_GENERATED = "generated"
CAT_RESERVED = "reserved"
# exemplo de uso (cliente de parceiro, demo): não é produto (fora do scan: stack, regras, convenções),
# mas também não é dado de teste — é código mantido por alguém e PODE ter dono de escrita.
CAT_EXAMPLE = "example"
CATEGORIES = (CAT_PRODUCT, CAT_FIXTURE, CAT_VENDOR, CAT_GENERATED, CAT_RESERVED, CAT_EXAMPLE)
IGNORED_CATEGORIES = frozenset([CAT_FIXTURE, CAT_VENDOR, CAT_GENERATED])
# fora da ANÁLISE do scan (ignoradas + exemplo); território: só IGNORED_CATEGORIES ficam de fora
NOT_ANALYZED_CATEGORIES = IGNORED_CATEGORIES | frozenset([CAT_EXAMPLE])

# Prefixos reservados ao harness/plataformas. Casamento por prefixo de path relativo.
RESERVED_PREFIXES = (
    STATE_DIR + "/",
    LEGACY_STATE_DIR + "/",
    ".claude/",
    ".cursor/",
    ".codex/",
    ".github/agents/",
    ".github/instructions/",
    "scripts/harness/",
)
# Saída da própria skill: nunca analisada (senão o scan leria a si mesmo).
SELF_PREFIXES = (STATE_DIR + "/",)

VENDOR_DIRS = frozenset(["vendor", "node_modules", "third_party", "third-party", "bower_components",
                         ".venv", "venv", "site-packages", "Pods", ".yarn"])
FIXTURE_DIRS = frozenset(["fixtures", "fixture", "__fixtures__", "testdata", "test-data", "test_data",
                          "golden", "goldens", "__snapshots__"])
# examples/ samples/ fora de pasta de teste = exemplo de uso; dentro de tests/ = fixture
EXAMPLE_DIRS = frozenset(["examples", "example", "samples", "sample"])
TEST_DIRS = frozenset(["tests", "test", "__tests__", "spec", "specs"])
GENERATED_DIRS = frozenset(["dist", "__pycache__", ".next", ".nuxt", "coverage", ".tox", "generated",
                            "__generated__", ".mypy_cache", ".pytest_cache", ".ruff_cache"])
GENERATED_FILE_RE = re.compile(
    r"(\.min\.(js|css)$|_pb2(_grpc)?\.pyi?$|\.pb\.go$|\.g\.dart$|\.generated\.[A-Za-z0-9]+$|"
    r"\.designer\.cs$|\.js\.map$|\.css\.map$|\.pyc$)")
GENERATED_MARKERS = (b"Code generated", b"@generated", b"<auto-generated", b"DO NOT EDIT")

LANG_BY_EXT = {
    ".py": "python", ".pyi": "python",
    ".js": "javascript", ".mjs": "javascript", ".cjs": "javascript", ".jsx": "javascript",
    ".ts": "typescript", ".tsx": "typescript", ".mts": "typescript", ".cts": "typescript",
    ".go": "go", ".java": "java", ".kt": "kotlin", ".kts": "kotlin", ".cs": "csharp",
    ".rb": "ruby", ".rs": "rust", ".php": "php", ".sh": "shell", ".bash": "shell",
    ".swift": "swift", ".c": "c", ".h": "c", ".cc": "cpp", ".cpp": "cpp", ".hpp": "cpp",
    ".scala": "scala", ".dart": "dart", ".lua": "lua", ".vue": "vue", ".svelte": "svelte",
    ".sql": "sql", ".md": "markdown", ".rst": "rst", ".json": "json", ".yml": "yaml",
    ".yaml": "yaml", ".toml": "toml", ".ini": "ini", ".cfg": "ini", ".xml": "xml",
    ".html": "html", ".css": "css", ".scss": "css",
}
CODE_LANGS = frozenset(["python", "javascript", "typescript", "go", "java", "kotlin", "csharp", "ruby",
                        "rust", "php", "shell", "swift", "c", "cpp", "scala", "dart", "lua", "vue",
                        "svelte"])


def resolve_target(arg=None):
    """Raiz do alvo (realpath). arg > $CLAUDE_PROJECT_DIR > cwd."""
    raw = arg or os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    root = os.path.realpath(os.path.expanduser(raw))
    if not os.path.isdir(root):
        raise CsError("alvo não é um diretório: %s" % raw,
                      "passe --target <repo> apontando para a raiz do repositório")
    return root


def state_root(target):
    """<alvo>/<STATE_DIR> (a pasta gerada pela skill)."""
    return os.path.join(target, STATE_DIR)


def specialists_dir(target):
    return os.path.join(target, SPECIALISTS_DIRNAME)


def facts_dir(target):
    return os.path.join(specialists_dir(target), "facts")


# Cabeçalho ÚNICO de facts/index.json5: o scan (rebuild) e o sync por camada (entrevista/lacunas gap.*,
# spotcheck) gravam o mesmo texto — conteúdo igual ⇒ bytes e hash iguais, sem churn no diff nem staleness falsa.
FACTS_INDEX_HEADER = "índice de fatos (id → camada) — gerado por cs.py scan e mantido por cs.py interview/facts"


def state_dir(target):
    return os.path.join(specialists_dir(target), "state")


def evidence_dir(target):
    return os.path.join(specialists_dir(target), "evidence")


def is_within(root, path):
    """True se realpath(path) está dentro de realpath(root) (ou é ele)."""
    r = os.path.realpath(root)
    p = os.path.realpath(path)
    return p == r or p.startswith(r.rstrip(os.sep) + os.sep)


def ensure_inside_specialists(target, path):
    """Guard de escrita: só <target>/<STATE_DIR>/**. Resolve symlinks do diretório pai."""
    sp = specialists_dir(os.path.realpath(target))
    parent = os.path.realpath(os.path.dirname(os.path.abspath(path)))
    full = os.path.join(parent, os.path.basename(path))
    if os.path.islink(full):
        raise CsError("recusa escrever em symlink: %s" % full, "remova o symlink em %s/" % STATE_DIR)
    if not (full == sp or full.startswith(sp + os.sep)):
        raise CsError("escrita fora de %s/ recusada: %s" % (STATE_DIR, path),
                      "a skill só escreve em <alvo>/%s/; isto é um bug do chamador" % STATE_DIR)
    return full


def rel_to_target(target, path):
    """Path relativo POSIX dentro do alvo (realpath). Erro se escapar do alvo."""
    if not is_within(target, path):
        raise CsError("path fora do alvo: %s" % path, "use paths dentro do repositório-alvo")
    rel = os.path.relpath(os.path.realpath(path), os.path.realpath(target))
    return "." if rel == "." else rel.replace(os.sep, "/")


def is_reserved(rel):
    """Prefixo reservado ao harness/plataformas (casamento por prefixo de path)."""
    r = rel[2:] if rel.startswith("./") else rel
    return any(r == p.rstrip("/") or r.startswith(p) for p in RESERVED_PREFIXES)


def is_self(rel):
    return any(rel == p.rstrip("/") or rel.startswith(p) for p in SELF_PREFIXES)


def classify(rel, head=None):
    """Categoria de um path relativo POSIX: vendor > fixture > example > generated > reserved > product.

    examples/ (ou samples/) sob uma pasta de teste é fixture; fora dela é `example`.

    head: primeiros bytes do arquivo (opcional) para detectar marcadores de código gerado.
    """
    parts = rel.split("/")
    dirs = parts[:-1]
    if any(d in VENDOR_DIRS for d in dirs):
        return CAT_VENDOR
    if any(d in FIXTURE_DIRS for d in dirs):
        return CAT_FIXTURE
    ex = next((i for i, d in enumerate(dirs) if d in EXAMPLE_DIRS), None)
    if ex is not None:
        return CAT_FIXTURE if any(d in TEST_DIRS for d in dirs[:ex]) else CAT_EXAMPLE
    if any(d in GENERATED_DIRS for d in dirs) or GENERATED_FILE_RE.search(parts[-1]):
        return CAT_GENERATED
    if head is not None and _has_generated_marker(head):
        return CAT_GENERATED
    if is_reserved(rel):
        return CAT_RESERVED
    return CAT_PRODUCT


def _has_generated_marker(head):
    first = b"\n".join(head.split(b"\n")[:5])
    if any(m in first for m in GENERATED_MARKERS[:3]):
        return True
    return b"DO NOT EDIT" in first and b"generated" in first.lower()


def lang_of(rel):
    base = rel.rsplit("/", 1)[-1]
    if base in ("Makefile", "makefile", "GNUmakefile"):
        return "make"
    if base == "Dockerfile" or base.startswith("Dockerfile."):
        return "docker"
    _, ext = os.path.splitext(base)
    return LANG_BY_EXT.get(ext.lower(), "other")


def is_code(rel):
    return lang_of(rel) in CODE_LANGS


_TEST_NAME_RE = re.compile(
    r"(^test_.*\.py$|_test\.py$|_test\.go$|\.(test|spec)\.[cm]?[jt]sx?$|Tests?\.(java|kt|cs)$|"
    r"_spec\.rb$|_test\.rb$|^test[_-].*\.(sh|bash)$|[_-]test\.(sh|bash)$|Test\.php$|_test\.rs$)")
_TEST_DIRS = frozenset(["tests", "test", "__tests__", "spec", "specs", "t"])


def is_test_file(rel):
    """Heurística por nome/diretório; só arquivos de código."""
    if not is_code(rel):
        return False
    parts = rel.split("/")
    if _TEST_NAME_RE.search(parts[-1]):
        return True
    return any(p in _TEST_DIRS for p in parts[:-1])


def component_of(rel, depth=None):
    """Componente = 1º diretório; se for raiz de código genérica (src/lib/packages/...), 2 níveis."""
    parts = rel.split("/")
    if len(parts) == 1:
        return "."
    roots = ("src", "lib", "packages", "apps", "services", "internal", "pkg", "cmd", "modules")
    if depth is None:
        depth = 2 if parts[0] in roots and len(parts) > 2 else 1
    return "/".join(parts[:depth])


def glob_to_regex(pattern):
    """Glob estilo gitignore simplificado: ** cruza diretórios, * e ? não cruzam '/'."""
    i, out = 0, []
    while i < len(pattern):
        c = pattern[i]
        if c == "*":
            if pattern[i:i + 3] == "**/":
                out.append("(?:.*/)?")
                i += 3
                continue
            if pattern[i:i + 2] == "**":
                out.append(".*")
                i += 2
                continue
            out.append("[^/]*")
        elif c == "?":
            out.append("[^/]")
        else:
            out.append(re.escape(c))
        i += 1
    return re.compile("^" + "".join(out) + "$")


_GLOB_CACHE = {}


def glob_match(rel, pattern):
    rx = _GLOB_CACHE.get(pattern)
    if rx is None:
        rx = _GLOB_CACHE[pattern] = glob_to_regex(pattern)
    return bool(rx.match(rel))


def expand_globs(files, patterns):
    """Arquivos (lista de rel paths) que casam com qualquer glob, ordenados."""
    return sorted(f for f in files if any(glob_match(f, p) for p in patterns))
